## NOTE: Main config moved to repo root /crowdin.yml
## This file kept for reference only.
## Source: /packages/website/locales/en.json
## Translation: /packages/website/locales/%two_letters_code%.json
