name: Deploy Edge to x86

on:
  push:
    branches: [ main ]
    paths:
      - 'orbiteos-edge/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orbiteos-edge

    steps:
    - uses: actions/checkout@v3

    - name: Copy files to Edge Server (x86)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EDGE_HOST }}
        username: ${{ secrets.EDGE_USERNAME }}
        password: ${{ secrets.EDGE_PASSWORD }}
        # key: ${{ secrets.EDGE_SSH_KEY }}
        source: "orbiteos-edge/*"
        target: "~/orbiteos-edge"
        strip_components: 1

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EDGE_HOST }}
        username: ${{ secrets.EDGE_USERNAME }}
        password: ${{ secrets.EDGE_PASSWORD }}
        # key: ${{ secrets.EDGE_SSH_KEY }}
        script: |
          # Cleanup existing Edge containers
          echo "Stopping existing Edge containers..."
          cd ~/orbiteos-edge
          docker compose down || true
          
          # Ensure directories exist
          mkdir -p config data

          echo "Deploying OrbitEOS Edge..."
          docker compose up -d --build --remove-orphans
          
          docker image prune -f
